{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "casinoshiz.fullname" . }}-postgres
  labels:
    {{- include "casinoshiz.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    {{- include "casinoshiz.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
