apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casinoshiz.fullname" . }}
  labels:
    {{- include "casinoshiz.labels" . | nindent 4 }}
type: Opaque
stringData:
  bot-token: {{ required "bot.token is required" .Values.bot.token | quote }}
  admin-web-token: {{ .Values.bot.adminWebToken | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  postgres-connection: {{ printf "Host=%s-postgres;Port=%d;Database=%s;Username=%s;Password=%s;Maximum Pool Size=100;Minimum Pool Size=5" (include "casinoshiz.fullname" .) (int .Values.postgres.port) .Values.postgres.database .Values.postgres.user .Values.postgres.password | quote }}
