apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    uid: clickhouse
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: analytics
      username: default
    secureJsonData:
      password: ""
    editable: true
