// <auto-generated />
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CasinoShiz.Migrations;

internal static class ModelSnapshotBuilder
{
    public static void Build(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("CasinoShiz.Data.Entities.ChatRegistration", b =>
        {
            b.Property<long>("ChatId").HasColumnType("INTEGER");
            b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
            b.Property<bool>("NotificationsEnabled").HasColumnType("INTEGER");
            b.Property<string>("Username").HasMaxLength(32).HasColumnType("TEXT");
            b.HasKey("ChatId");
            b.ToTable("Chats");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.DisplayNameOverride", b =>
        {
            b.Property<string>("OriginalName").HasMaxLength(64).HasColumnType("TEXT");
            b.Property<string>("NewName").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
            b.HasKey("OriginalName");
            b.ToTable("DisplayNameOverrides");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.FreespinCode", b =>
        {
            b.Property<System.Guid>("Code").HasColumnType("TEXT");
            b.Property<bool>("Active").HasColumnType("INTEGER");
            b.Property<long?>("ChatId").HasColumnType("INTEGER");
            b.Property<long>("IssuedAt").HasColumnType("INTEGER");
            b.Property<long>("IssuedBy").HasColumnType("INTEGER");
            b.Property<int?>("MessageId").HasColumnType("INTEGER");
            b.HasKey("Code");
            b.HasIndex("Active");
            b.ToTable("FreespinCodes");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.HorseBet", b =>
        {
            b.Property<System.Guid>("Id").HasColumnType("TEXT");
            b.Property<int>("Amount").HasColumnType("INTEGER");
            b.Property<int>("HorseId").HasColumnType("INTEGER");
            b.Property<string>("RaceDate").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
            b.Property<long>("UserId").HasColumnType("INTEGER");
            b.HasKey("Id");
            b.HasIndex("RaceDate", "UserId");
            b.ToTable("HorseBets");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.HorseResult", b =>
        {
            b.Property<string>("RaceDate").HasMaxLength(10).HasColumnType("TEXT");
            b.Property<byte[]>("ImageData").IsRequired().HasColumnType("BLOB");
            b.Property<int>("Winner").HasColumnType("INTEGER");
            b.HasKey("RaceDate");
            b.ToTable("HorseResults");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.PokerSeat", b =>
        {
            b.Property<string>("InviteCode").HasMaxLength(8).HasColumnType("TEXT");
            b.Property<int>("Position").HasColumnType("INTEGER");
            b.Property<long>("ChatId").HasColumnType("INTEGER");
            b.Property<int>("CurrentBet").HasColumnType("INTEGER");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
            b.Property<bool>("HasActedThisRound").HasColumnType("INTEGER");
            b.Property<string>("HoleCards").IsRequired().HasMaxLength(8).HasColumnType("TEXT");
            b.Property<long>("JoinedAt").HasColumnType("INTEGER");
            b.Property<int>("Stack").HasColumnType("INTEGER");
            b.Property<int?>("StateMessageId").HasColumnType("INTEGER");
            b.Property<int>("Status").HasColumnType("INTEGER");
            b.Property<long>("UserId").HasColumnType("INTEGER");
            b.HasKey("InviteCode", "Position");
            b.HasIndex("UserId");
            b.ToTable("PokerSeats");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.PokerTable", b =>
        {
            b.Property<string>("InviteCode").HasMaxLength(8).HasColumnType("TEXT");
            b.Property<int>("BigBlind").HasColumnType("INTEGER");
            b.Property<int>("ButtonSeat").HasColumnType("INTEGER");
            b.Property<string>("CommunityCards").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
            b.Property<long>("CreatedAt").HasColumnType("INTEGER");
            b.Property<int>("CurrentBet").HasColumnType("INTEGER");
            b.Property<int>("CurrentSeat").HasColumnType("INTEGER");
            b.Property<string>("DeckState").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
            b.Property<long>("HostUserId").HasColumnType("INTEGER");
            b.Property<long>("LastActionAt").HasColumnType("INTEGER");
            b.Property<int>("MinRaise").HasColumnType("INTEGER");
            b.Property<int>("Phase").HasColumnType("INTEGER");
            b.Property<int>("Pot").HasColumnType("INTEGER");
            b.Property<int>("SmallBlind").HasColumnType("INTEGER");
            b.Property<int>("Status").HasColumnType("INTEGER");
            b.HasKey("InviteCode");
            b.HasIndex("Status");
            b.ToTable("PokerTables");
        });

        modelBuilder.Entity("CasinoShiz.Data.Entities.UserState", b =>
        {
            b.Property<long>("TelegramUserId").HasColumnType("INTEGER");
            b.Property<int>("AttemptCount").HasColumnType("INTEGER");
            b.Property<int>("Coins").HasColumnType("INTEGER");
            b.Property<string>("DisplayName").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
            b.Property<int>("ExtraAttempts").HasColumnType("INTEGER");
            b.Property<long>("LastDayUtc").HasColumnType("INTEGER");
            b.HasKey("TelegramUserId");
            b.ToTable("Users");
        });
    }
}
