// <auto-generated />

using CasinoShiz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasinoShiz.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260422000000_AddSecretHitler")]
partial class AddSecretHitler
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        ModelSnapshotBuilder.Build(modelBuilder);
    }
}
