bot:
  token: "7871475466:AAGDSaIFy105lkOnKB4Ux8cMQ7ELXFwdVHc"
  username: "@CazinoShizBot"
  admins:
    - 925337014
  readOnlyAdmins: []

postgres:
  password: "changeme"

redis:
  enabled: true
  password: ""

games:
  horse:
    admins:
      - 925337014
